// <auto-generated />
namespace Teste.GitHub.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TesteSegundaFeira : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TesteSegundaFeira));
        
        string IMigrationMetadata.Id
        {
            get { return "201702061514065_TesteSegundaFeira"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
