// <auto-generated />
namespace Teste.GitHub.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserMApeamento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserMApeamento));
        
        string IMigrationMetadata.Id
        {
            get { return "201702091531179_UserMApeamento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
